### ISSUE TITLE
Option throws error when not a string type

### ISSUE THREAD

**Issue by PillageDev** [MusaBrt/KCommando#17]
**Describe the bug**
When you make an option other than type string, it will throw an error

**To Reproduce**
Add an option to any slash command with type User or Integer (didn't test other ones)

**Expected behavior**
Not throw an error and proceed on initialization  

**Screenshots**
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot add string choice for OptionType.USER
        at net.dv8tion.jda.api.interactions.commands.build.OptionData.addChoice(OptionData.java:926)
        at me.koply.kcommando.integration.impl.jda.JDAIntegration.registerSlashCommand(JDAIntegration.java:90)
        at me.koply.kcommando.boot.KInitializer.registerSlashBox(KInitializer.java:77)
        at me.koply.kcommando.boot.KInitializer.registerBoxWithInstance(KInitializer.java:124)
        at me.koply.kcommando.boot.KInitializer.registerBox(KInitializer.java:146)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at me.koply.kcommando.boot.KInitializer.build(KInitializer.java:52)
        at me.koply.kcommando.KCommando.build(KCommando.java:52)
        at dev.tiertests.Main.main(Main.java:91)
```

**Versions**
JDA: 5.0.0-beta.21
Reflections8: 0.11.5
KCommando: 5.1.0

**Additional context**

**Comment by PillageDev** [comment]
Required me to add 
```java
if (!(option.type() == me.koply.kcommando.internal.OptionType.STRING)) {
    continue;
}
```
when registering the command because of the default choice option.
